config/routes.rb
Rails.application.routes.draw do
 #HTTP verb, url(location), hash rocket, controller, method
 get '/blogs' => 'blog#index', as: 'blogs'
 get '/blogs/new' => 'blog#new', as: 'new_blog'
 get '/blogs/:id' => 'blog#show', as: 'blog'
 get '/blogs/:id/edit' => 'blog#edit', as: 'edit_blog'
 post '/blogs' => 'blog#create'
 patch '/blogs/:id' => 'blog#update'
 delete '/blogs/:id' => 'blog#destroy', as: 'delete_blog'
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :content, presence: true
    validates :title, :content, uniqueness: true
    validates :title, length: {minimum: 4}
    validates :content, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

    def index
        @blogs = Blog.all
    end

    def show
        @blog = Blog.find(params[:id])
    end

    def new
        @blog = Blog.new
    end

    def create
        @blog = Blog.create(blog_params)
        if @blog.valid?
            redirect_to blogs_path
        end
    end

    def destroy
        @blog = Blog.find(params[:id])
        if @blog.destroy
        redirect_to blogs_path
        end
    end

    def edit 
        @blog = Blog.find(params[:id])
    end

    def update
        @blog = Blog.find(params[:id])
        @blog.update(blog_params)
        if @blog.valid?
        redirect_to blog_path(@blog.id)
        end
    end

    private 
    def blog_params
        params.require(:blog).permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h2>Edit a new Blog</h2>

<%= form_with model: @blog do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :content %>
  <%= form.text_field :content %>

  <%= form.submit "Update Blog" %>
<% end %>
<h1><%= link_to 'All the Blogs', blogs_path %></h1>

app/views/blog/index.html.erb
<h1>Blog Post App </h1>

<ul>
    <% @blogs.each do |blog| %>
        <li><%= link_to blog.title, blog_path(blog.id) %></li>
    <% end %>
</ul>

<p><%= link_to 'Add New Blog', new_blog_path %></p>

app/views/blog/new.html.erb
<h2>Add a new Blog</h2>

<%= form_with model: @blog do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :content %>
  <%= form.text_field :content %>

  <%= form.submit "Add Blog" %>
<% end %>

app/views/blog/show.html.erb
<h1><%= @blog.title %></h1>

</br>
<h1><%=  @blog.content %></h1>
<h1><%= link_to 'All the Blogs', blogs_path %></h1>
<h1><%= link_to 'Edit Blog', edit_blog_path %></h1>
<h1><%= button_to 'Remove Blog', delete_blog_path, method: :delete %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogChallengeMannyMike</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>